### ISSUE TITLE
Ease of Use Issues

### ISSUE THREAD

**Issue by feliciachang** [sarimabbas/ts-chaos#3]
- being able to move the app with the top bar at all times
- copy and pasting screenshots into assets
- code blocks in markdown
- being able to link parts of a webpage to the notes
- opening pdfs
- navigation and keyboard inputs on web pages

**Comment by sarimabbas** [comment]
- [ ] being able to move the app with the top bar at all times

- [ ] copy and pasting screenshots into assets

- [x] code blocks in markdown

- [x] being able to link parts of a webpage to the notes

Completed parially in 0.8.0

- [x] opening pdfs

You can add PDF assets and point the webview to them by modifying its URL. Will also add support for PDFs in the preview area in a future release

- [x] navigation and keyboard inputs on web pages

Added home button in 0.8.0. Will add forward and backward buttons, and a right click menu in a future release.

**Comment by feliciachang** [comment]
- [ ] left hand side link disappears after you leave the page
