### ISSUE TITLE
Aesthetics 

### ISSUE THREAD

**Issue by feliciachang** [sarimabbas/ts-chaos#4]
- information hierarchy with markdown preview
- collapsibility of left side nav bar

**Comment by sarimabbas** [comment]
Since 0.9.0, there isn't a notes editor, only two webviews, so the markdown preview has been disabled. might come back to a local notes editor in the future

Will work on the left side bar collapse

**Comment by feliciachang** [comment]
- [ ] would be great to zoom in and out of webpages

**Comment by sarimabbas** [comment]
Gonna make separate issues for both of these and close this one!
